#! /bin/bash

source "${APPDIR}/py_version.sh"
# Export APPRUN if running from an extracted image
self="$(readlink -f -- $0)"
here="${self%/*}"
APPDIR="${APPDIR:-${here}}"

# Export TCl/Tk
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcl8.5"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tk8.5"
export TKPATH="${TK_LIBRARY}"

# Export SSL certificate
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

export LC_ALL=C

# Call the entry point
#! /bin/bash
${APPDIR}/usr/bin/${PY_STR} "${APPDIR}/opt/${PY_STR}/bin/osc-cli" "$@"
